# Generated by Django 3.2.8 on 2021-12-20 07:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baithi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=155)),
                ('thoigian', models.DateTimeField(default=datetime.datetime(2021, 12, 20, 7, 17, 19, 72497, tzinfo=utc))),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
