# Generated by Django 3.2.8 on 2021-12-21 13:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quanlybaithi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baithi',
            name='thoigian',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 13, 39, 46, 500880, tzinfo=utc)),
        ),
    ]
