# Generated by Django 3.2.8 on 2021-12-21 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quanlybaithi', '0002_alter_baithi_thoigian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baithi',
            name='thoigian',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 13, 48, 29, 263571, tzinfo=utc)),
        ),
    ]
