# Generated by Django 3.2.8 on 2021-12-22 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quanlybaithi', '0003_alter_baithi_thoigian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baithi',
            name='thoigian',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 22, 8, 54, 11, 644630, tzinfo=utc)),
        ),
    ]
