# Generated by Django 3.2.8 on 2021-12-24 06:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quanlybaithi', '0004_alter_baithi_thoigian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baithi',
            name='thoigian',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 6, 10, 41, 156476, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Bailam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=155)),
                ('bai', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('baithi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlybaithi.baithi')),
            ],
        ),
    ]
