# Generated by Django 3.2.8 on 2021-12-24 08:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quanlybaithi', '0005_auto_20211224_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='baithi',
            name='ketqua',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='baithi',
            name='thoigian',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 8, 49, 58, 869016, tzinfo=utc)),
        ),
    ]
