# Generated by Django 3.2.8 on 2021-12-25 02:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quanlybaithi', '0006_auto_20211224_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailam',
            name='diem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baithi',
            name='thoigian',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 2, 35, 50, 510168, tzinfo=utc)),
        ),
    ]
