# Generated by Django 3.2.8 on 2021-12-25 02:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quanlybaithi', '0007_auto_20211225_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='baithi',
            name='socau',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baithi',
            name='thoigian',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 25, 2, 52, 50, 790750, tzinfo=utc)),
        ),
    ]
