# Generated by Django 3.2.8 on 2021-12-26 02:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quanlybaithi', '0008_auto_20211225_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailam',
            name='sbd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='baithi',
            name='thoigian',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 2, 17, 4, 458141, tzinfo=utc)),
        ),
    ]
