# Generated by Django 3.2.8 on 2021-12-26 03:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quanlybaithi', '0009_auto_20211226_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailam',
            name='made',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='bailam',
            name='sbd',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='baithi',
            name='thoigian',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 3, 14, 6, 612702, tzinfo=utc)),
        ),
    ]
