# Generated by Django 3.2.8 on 2021-12-26 04:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quanlybaithi', '0010_auto_20211226_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baithi',
            name='thoigian',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 4, 46, 4, 301731, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Bodapan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dapan', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('bmade', models.CharField(max_length=15, null=True)),
                ('baithi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quanlybaithi.baithi')),
            ],
        ),
    ]
